/**
 * Canonical rental-contract clauses for VELTO MOBILITY.
 *
 * Source of truth for the legal body of every contract generated by the
 * system. The PDF renderer (functions/src/contracts/pdf.ts) takes the
 * `ContractClauses` bundle from the contract document and formats it;
 * the public sign page shows the same highlights.
 *
 * Why here, not in src/assets/i18n?
 *   - The contract body has legal weight and is reviewed by the company,
 *     not the app's i18n owner.
 *   - It must be available inside Cloud Functions (Node) without shipping
 *     the SPA bundle.
 *   - Versions are versioned alongside the contract — older contracts
 *     stay reproducible even if this file is edited later.
 *
 * IMPORTANT — these clauses include specific references to Spanish
 * regulations (Ley sobre Responsabilidad Civil y Seguro en la Circulación
 * de Vehículos a Motor, Código Penal arts. 237, 244, 263, 264, 468,
 * Ley Orgánica 3/2018 LOPDGDD, RGPD 2016/679). If the company operates
 * outside Spain, the legal references must be reviewed and adapted.
 */

import type {
  ContractClauses,
  ContractClauseBundle,
  ContractLocale
} from './contract-types';

const CLAUSES_VERSION = 2;

// ---------------------------------------------------------------------------
// Canonical clause ids, used to bind translations together.
// ---------------------------------------------------------------------------
type ClauseId =
  | 'parties'
  | 'authorized_drivers'
  | 'rental_period'
  | 'price_and_deposit'
  | 'mileage'
  | 'fuel_and_cleanliness'
  | 'legal_use'
  | 'geographic_limits'
  | 'fines_penalties'
  | 'damages_intentional'
  | 'theft_unreturned'
  | 'incidents'
  | 'insurance'
  | 'data_protection'
  | 'jurisdiction';

interface LocalizedClause {
  title: string;
  body: string[];
}

const I18N: Record<ClauseId, Record<ContractLocale, LocalizedClause>> = {
  parties: {
    es: {
      title: '1. REUNIDOS Y OBJETO DEL CONTRATO',
      body: [
        'De una parte, el ARRENDADOR (la Sociedad) identificado en la cabecera de este documento, dedicado al alquiler de vehículos sin conductor, y de otra parte el ARRENDATARIO, persona física identificada en la cabecera, con capacidad legal suficiente para obligarse, formalizan el presente contrato de arrendamiento de vehículo sin conductor.',
        'El ARRENDADOR cede temporalmente al ARRENDATARIO el uso del vehículo descrito en la sección "Datos del vehículo" y el ARRENDATARIO acepta las condiciones del presente contrato, declarando recibir el vehículo en correcto estado de funcionamiento, limpieza, conservación y dotación (incluyendo rueda de repuesto o kit antipinchazos, triángulos de preseñalización o baliza de preseñalización V16 conectada, chaleco reflectante, documentación del vehículo y un juego de llaves). El detalle de la dotación entregada y el estado del vehículo se recogen en el parte de entrega, documentado con fotografías en el momento de la entrega, que el ARRENDADOR conserva y pone a disposición del ARRENDATARIO a su solicitud, y que forma parte inseparable de este contrato.'
      ]
    },
    en: {
      title: '1. PARTIES AND PURPOSE OF THE CONTRACT',
      body: [
        'On one side, the LESSOR (the Company) identified in the header of this document, engaged in the activity of renting vehicles without a driver, and on the other side the RENTER, a natural person identified in the header, with sufficient legal capacity to be bound, execute this vehicle-rental contract without driver.',
        'The LESSOR temporarily transfers to the RENTER the use of the vehicle described in the "Vehicle data" section, and the RENTER accepts the conditions of this contract, declaring that they receive the vehicle in correct working order, clean, well preserved and equipped (including spare wheel or anti-puncture kit, warning triangles or a connected V16 emergency beacon, high-visibility vest, vehicle documents and a set of keys). The detail of the equipment handed over and the condition of the vehicle are recorded in the pick-up report, documented with photographs taken at handover, which the LESSOR keeps and makes available to the RENTER on request, and which forms an inseparable part of this contract.'
      ]
    },
    ro: {
      title: '1. PĂRȚI ȘI OBIECTUL CONTRACTULUI',
      body: [
        'De o parte, LOCATORUL (Societatea) identificat în antetul acestui document, care desfășoară activitatea de închiriere de vehicule fără șofer, iar de cealaltă parte LOCATARUL, persoană fizică identificată în antet, cu capacitate legală suficientă pentru a se obliga, încheie prezentul contract de închiriere a unui vehicul fără șofer.',
        'LOCATORUL cedează temporar LOCATARULUI folosința vehiculului descris în secțiunea "Datele vehiculului", iar LOCATARUL acceptă condițiile prezentului contract, declarând că primește vehiculul în stare corectă de funcționare, curățenie, conservare și dotare (inclusiv roata de rezervă sau kitul antipană, triunghiurile de presemnalizare sau baliza de semnalizare V16 conectată, vesta reflectorizantă, documentele vehiculului și un set de chei). Detaliul dotării predate și starea vehiculului se consemnează în procesul-verbal de predare, documentat cu fotografii în momentul predării, pe care LOCATORUL îl păstrează și îl pune la dispoziția LOCATARULUI la cererea acestuia, și care face parte integrantă din prezentul contract.'
      ]
    }
  },
  authorized_drivers: {
    es: {
      title: '2. CONDUCTORES AUTORIZADOS Y EDAD MÍNIMA',
      body: [
        'El ARRENDATARIO es el único conductor autorizado por defecto. Únicamente podrán conducir el vehículo las personas expresamente declaradas por el ARRENDADOR al inicio del alquiler e identificadas nominalmente en el presente contrato.',
        'La edad mínima para alquilar cualquier categoría de vehículo es de 21 años cumplidos, y la edad máxima es de 75 años. En categorías especiales la edad mínima podrá ser superior. El conductor deberá estar en posesión de un permiso de conducir válido en España (o válido en la UE con traducción jurada cuando proceda) con una antigüedad mínima de un (1) año en la categoría correspondiente al vehículo alquilado.',
        'El ARRENDATARIO garantiza que todas las personas que conduzcan el vehículo cumplen los requisitos anteriores. La conducción por persona no autorizada constituye incumplimiento grave del contrato, facultando al ARRENDADOR para resolver el contrato, retirar el vehículo e iniciar las acciones legales que correspondan, sin perjuicio de la responsabilidad penal, civil y administrativa del conductor no autorizado.'
      ]
    },
    en: {
      title: '2. AUTHORISED DRIVERS AND MINIMUM AGE',
      body: [
        'The RENTER is the only authorised driver by default. Only persons expressly declared by the LESSOR at the start of the rental may drive the vehicle, identified by name in this contract.',
        'The minimum age to rent any vehicle category is 21 (completed), and the maximum is 75. Special categories may require a higher minimum age. The driver must hold a valid driving licence in Spain (or valid in the EU with a sworn translation if applicable) with at least one (1) year of seniority in the category corresponding to the rented vehicle.',
        'The RENTER guarantees that every person driving the vehicle meets the above requirements. Driving by an unauthorised person is a serious breach, empowering the LESSOR to terminate the contract, withdraw the vehicle and bring any applicable legal action, without prejudice to the criminal, civil and administrative liability of the unauthorised driver.'
      ]
    },
    ro: {
      title: '2. CONDUCĂTORI AUTORIZAȚI ȘI VÂRSTA MINIMĂ',
      body: [
        'LOCATARUL este singurul conducător autorizat în mod implicit. Pot conduce vehiculul doar persoanele declarate în mod expres de LOCATOR la începutul închirierii, identificate nominal în prezentul contract.',
        'Vârsta minimă pentru a închiria orice categorie de vehicul este de 21 de ani împliniți, iar vârsta maximă este de 75 de ani. La categoriile speciale vârsta minimă poate fi mai mare. Conducătorul trebuie să dețină un permis de conducere valabil în Spania (sau valabil în UE cu traducere legalizată, dacă este cazul) cu o vechime de cel puțin un (1) an în categoria corespunzătoare vehiculului închiriat.',
        'LOCATARUL garantează că toate persoanele care conduc vehiculul îndeplinesc cerințele de mai sus. Conducerea de către o persoană neautorizată constituie încălcare gravă a contractului, îndreptățind LOCATORUL să rezilieze contractul, să retragă vehiculul și să inițieze acțiunile legale corespunzătoare, fără a aduce atingere răspunderii penale, civile și administrative a conducătorului neautorizat.'
      ]
    }
  },
  rental_period: {
    es: {
      title: '3. PERÍODO DE ALQUILER, ENTREGA Y DEVOLUCIÓN',
      body: [
        'El período de alquiler comienza en la fecha, hora y lugar pactados para la entrega y finaliza en la fecha, hora y lugar pactados para la devolución, tal y como consta en la sección "Datos de la reserva". Cualquier modificación de fechas, horas o lugares requiere acuerdo escrito entre las partes (puede ser por correo electrónico).',
        'El retraso en la devolución superior a treinta (30) minutos sobre la hora pactada, sin autorización del ARRENDADOR, facultará a éste para cobrar un día adicional de alquiler por cada fracción de 24 horas o, en su caso, a iniciar las acciones legales que correspondan por retención indebida del vehículo, de conformidad con los artículos 237 y 244 del Código Penal.',
        'Si la devolución se realizase en una oficina o ubicación distinta a la pactada, el ARRENDATARIO abonará el suplemento de "one-way" o devolución en oficina distinta vigente en el momento de la devolución, salvo pacto expreso en contrario.'
      ]
    },
    en: {
      title: '3. RENTAL PERIOD, DELIVERY AND RETURN',
      body: [
        'The rental period begins on the date, time and place agreed for delivery and ends on the date, time and place agreed for return, as set out in the "Reservation data" section. Any modification requires written agreement of the parties (e-mail is acceptable).',
        'A delay of more than thirty (30) minutes over the agreed time, without the LESSOR\'s authorisation, empowers the LESSOR to charge an additional day for every 24-hour period, or to bring legal action for the unlawful retention of the vehicle under articles 237 and 244 of the Spanish Criminal Code.',
        'If the vehicle is returned to a different office or location than the one agreed, the RENTER will pay the "one-way" or different-office return supplement in force at the time of return, unless expressly agreed otherwise.'
      ]
    },
    ro: {
      title: '3. PERIOADA DE ÎNCHIRIERE, PREDARE ȘI RETURNARE',
      body: [
        'Perioada de închiriere începe la data, ora și locul convenite pentru predare și se termină la data, ora și locul convenite pentru returnare, conform celor din secțiunea "Datele rezervării". Orice modificare a datelor, orelor sau locurilor necesită acordul scris al părților (e-mailul este acceptabil).',
        'Întârzierea la returnare mai mare de treizeci (30) de minute peste ora convenită, fără autorizarea LOCATORULUI, îl îndreptățește pe acesta să perceapă o zi suplimentară de închiriere pentru fiecare fracțiune de 24 de ore sau, dacă este cazul, să inițieze acțiunile legale corespunzătoare pentru reținerea neîntemeiată a vehiculului, în conformitate cu articolele 237 și 244 din Codul Penal spaniol.',
        'Dacă returnarea se face la un birou sau locație diferită de cea convenită, LOCATARUL va plăti suplimentul "one-way" sau de returnare la birou diferit în vigoare la momentul returnării, dacă nu se convine altfel în mod expres.'
      ]
    }
  },
  price_and_deposit: {
    es: {
      title: '4. PRECIO, FIANZA Y DEPÓSITO',
      body: [
        'El precio total del alquiler, incluyendo todos los conceptos pactados (tarifa base, kilometraje, seguros, tasas aeroportuarias si las hubiere, IVA aplicable y cualesquiera otros suplementos), figura desglosado en la sección "Precio y fianza" del presente contrato. Cualquier cargo adicional aplicable se calculará al cierre del alquiler y se cobrará de la fianza o del medio de pago facilitado por el ARRENDATARIO.',
        'El ARRENDATARIO entrega en este acto, en concepto de fianza, la cantidad indicada en la sección "Precio y fianza", que se deposita para responder del cumplimiento de las obligaciones derivadas de este contrato. La fianza se devolverá íntegramente en un plazo máximo de treinta (30) días desde la fecha de devolución del vehículo, una vez verificado el estado del vehículo, descontados, en su caso, los importes correspondientes a daños, combustible, multas, peajes, gastos de gestión y cualquier otra cantidad adeudada por el ARRENDATARIO.',
        'El ARRENDATARIO autoriza expresamente al ARRENDADOR a cargar en el medio de pago facilitado los importes que resulten exigibles conforme a este contrato: el precio del alquiler y los suplementos pactados, los kilómetros adicionales, el combustible no repuesto, la limpieza extraordinaria, los daños, las multas y sanciones, y cualquier otra cantidad adeudada. Todo cargo posterior a la devolución se comunicará previamente al ARRENDATARIO con el detalle y el justificante del importe.',
        'La fianza podrá ser retenida, en todo o en parte, para hacer frente a: (i) reparaciones por daños no cubiertos por el seguro o franquicia; (ii) repostaje de combustible no devuelto; (iii) limpieza extraordinaria; (iv) pérdida, robo o deterioro de llaves, documentos o accesorios; (v) peajes, multas o sanciones administrativas o penales no satisfechas; (vi) días de alquiler adicionales por devolución tardía; y (vii) cualquier otra obligación económica derivada del incumplimiento del contrato.'
      ]
    },
    en: {
      title: '4. PRICE AND SECURITY DEPOSIT',
      body: [
        'The total rental price, including all agreed items (base rate, mileage, insurance, airport fees if any, applicable VAT and any other supplements), is itemised in the "Price and deposit" section. Any applicable additional charge will be calculated at the close of the rental and charged against the deposit or against the payment method provided by the RENTER.',
        'The RENTER delivers in this act, by way of security deposit, the amount shown in the "Price and deposit" section, as collateral for the obligations arising from this contract. The deposit will be returned in full within a maximum of thirty (30) days from the date of return of the vehicle, once the vehicle\'s condition has been verified, deducting, if applicable, the amounts corresponding to damage, fuel, fines, tolls, administrative costs and any other amount owed by the RENTER.',
        'The RENTER expressly authorises the LESSOR to charge to the payment method provided any amounts due under this contract: the rental price and agreed supplements, additional kilometres, unreplaced fuel, extraordinary cleaning, damage, fines and sanctions, and any other amount owed. Any charge made after the return of the vehicle will be notified to the RENTER in advance, with a breakdown and supporting evidence of the amount.',
        'The deposit may be retained, in whole or in part, to cover: (i) repairs for damage not covered by the insurance or franchise; (ii) refuelling of unreturned fuel; (iii) extraordinary cleaning; (iv) loss, theft or deterioration of keys, documents or accessories; (v) tolls, fines or administrative or criminal sanctions not satisfied; (vi) additional rental days due to late return; and (vii) any other economic obligation derived from breach of the contract.'
      ]
    },
    ro: {
      title: '4. PREȚ ȘI GARANȚIE',
      body: [
        'Prețul total al închirierii, incluzând toate elementele convenite (tarif de bază, kilometraj, asigurări, taxe aeroportuare dacă există, TVA aplicabil și orice alte suplimente), este defalcat în secțiunea "Preț și garanție". Orice taxă suplimentară aplicabilă se va calcula la închiderea închirierii și se va încasa din garanție sau din metoda de plată furnizată de LOCATAR.',
        'LOCATARUL predă prin prezentul act, cu titlu de garanție, suma indicată în secțiunea "Preț și garanție", care se depune pentru a garanta îndeplinirea obligațiilor ce decurg din acest contract. Garanția va fi returnată integral în termen de maximum treizeci (30) de zile de la data returnării vehiculului, după verificarea stării vehiculului, scăzându-se, dacă este cazul, sumele corespunzătoare daunelor, combustibilului, amenzilor, taxelor de autostradă, cheltuielilor de gestionare și oricărei alte sume datorate de LOCATAR.',
        'LOCATARUL autorizează în mod expres LOCATORUL să debiteze metoda de plată furnizată cu sumele datorate în temeiul acestui contract: prețul închirierii și suplimentele convenite, kilometrii suplimentari, combustibilul nerealimentat, curățenia extraordinară, daunele, amenzile și sancțiunile, precum și orice altă sumă datorată. Orice debitare ulterioară returnării vehiculului va fi comunicată în prealabil LOCATARULUI, cu detalierea și documentul justificativ al sumei.',
        'Garanția poate fi reținută, în tot sau în parte, pentru a acoperi: (i) reparații pentru daune neacoperite de asigurare sau franciză; (ii) realimentarea cu combustibil nerestituit; (iii) curățenia extraordinară; (iv) pierderea, furtul sau deteriorarea cheilor, documentelor sau accesoriilor; (v) taxele de autostradă, amenzile sau sancțiunile administrative sau penale nesatisfăcute; (vi) zile suplimentare de închiriere cauzate de returnarea cu întârziere; și (vii) orice altă obligație economică derivată din neîndeplinirea contractului.'
      ]
    }
  },
  /**
   * Kilometraje.
   *
   * ⚠️ **Sin esta cláusula el cargo por kilómetros no estaba pactado.** La
   * aplicación sabía calcularlo desde el principio —la ficha del vehículo lleva
   * los kilómetros incluidos y el precio del extra, y la devolución lo sugiere—
   * pero el contrato no lo mencionaba ni una vez. Cobrar por algo que el
   * documento firmado no dice es lo primero que un cliente discute, y con razón.
   */
  mileage: {
    es: {
      title: '5. KILOMETRAJE INCLUIDO Y KILÓMETROS ADICIONALES',
      body: [
        'El alquiler incluye el número de kilómetros indicado en la sección "Precio y fianza", resultado de multiplicar los kilómetros diarios allí expresados por los días de duración del alquiler. Los kilómetros incluidos y no recorridos no son reembolsables ni acumulables a otro alquiler.',
        'Los kilómetros que excedan de los incluidos se facturarán al precio por kilómetro indicado en esa misma sección. El cómputo se obtiene por diferencia entre la lectura del cuentakilómetros en la entrega y en la devolución, ambas reflejadas y fotografiadas en los partes de entrega y devolución, que el ARRENDADOR conserva, pone a disposición del ARRENDATARIO a su solicitud, y que forman parte inseparable de este contrato.',
        'La manipulación, desconexión, sustitución o alteración del cuentakilómetros constituye incumplimiento grave del contrato y facultará al ARRENDADOR para facturar el kilometraje conforme a estimación pericial, además de ejercer las acciones civiles y penales que correspondan.'
      ]
    },
    en: {
      title: '5. INCLUDED MILEAGE AND ADDITIONAL KILOMETRES',
      body: [
        'The rental includes the number of kilometres shown in the "Price and deposit" section, being the daily allowance stated there multiplied by the number of rental days. Included kilometres that are not driven are neither refundable nor transferable to another rental.',
        'Kilometres driven in excess of those included will be charged at the per-kilometre price shown in that same section. The count is the difference between the odometer reading at handover and at return, both recorded and photographed in the pick-up and return reports, which the LESSOR keeps, makes available to the RENTER on request, and which form an inseparable part of this contract.',
        'Tampering with, disconnecting, replacing or altering the odometer constitutes a serious breach of this contract and entitles the LESSOR to invoice mileage on the basis of an expert estimate, in addition to pursuing any applicable civil and criminal action.'
      ]
    },
    ro: {
      title: '5. KILOMETRAJ INCLUS ȘI KILOMETRI SUPLIMENTARI',
      body: [
        'Închirierea include numărul de kilometri indicat în secțiunea "Preț și garanție", rezultat din înmulțirea kilometrilor zilnici menționați acolo cu numărul de zile de închiriere. Kilometrii incluși și neparcurși nu se rambursează și nu se pot reporta la o altă închiriere.',
        'Kilometrii care depășesc numărul inclus se facturează la prețul pe kilometru indicat în aceeași secțiune. Calculul se face prin diferența dintre indicația kilometrajului la predare și la returnare, ambele consemnate și fotografiate în procesele-verbale de predare și de returnare, pe care LOCATORUL le păstrează, le pune la dispoziția LOCATARULUI la cererea acestuia, și care fac parte integrantă din acest contract.',
        'Manipularea, deconectarea, înlocuirea sau alterarea kilometrajului constituie o încălcare gravă a contractului și dă dreptul LOCATORULUI să factureze kilometrajul pe baza unei estimări de specialitate, pe lângă exercitarea acțiunilor civile și penale corespunzătoare.'
      ]
    }
  },
  fuel_and_cleanliness: {
    es: {
      title: '6. COMBUSTIBLE, LIMPIEZA Y MANTENIMIENTO',
      body: [
        'El vehículo se entrega con el nivel de combustible que se haga constar y se fotografíe en el parte de entrega, y debe devolverse con ese mismo nivel, que se comprueba y se refleja en el parte de devolución. Si el nivel de devolución fuera inferior, se cobrará el repostaje al precio vigente en el momento de la devolución más un suplemento de gestión. Si el vehículo se devolviese con un nivel de combustible superior al de entrega, no se abonará cantidad alguna por la diferencia.',
        'El vehículo se devuelve en el mismo estado de limpieza en que se entregó. Cuando el vehículo se devuelva con condiciones de suciedad extraordinarias (vómito, barro, arena, pelos de animal, restos orgánicos, mal olor persistente, manchas no habituales, residuos en tapicería) el ARRENDADOR podrá cobrar al ARRENDATARIO los gastos de limpieza extraordinaria, con un mínimo equivalente a una hora de servicio profesional de detailing.',
        'El ARRENDATARIO se obliga a comprobar periódicamente los niveles de aceite, refrigerante, líquido de frenos y presión de los neumáticos, y a atender a las indicaciones del cuadro de instrumentos, asumiendo los gastos derivados del uso negligente del vehículo (incluido el repostaje de combustible inadecuado).'
      ]
    },
    en: {
      title: '6. FUEL, CLEANLINESS AND MAINTENANCE',
      body: [
        'The vehicle is delivered with the fuel level recorded and photographed in the pick-up report, and must be returned with that same level, which is checked and recorded in the return report. If the return level is lower, refuelling will be charged at the price in force at the time of return plus a handling surcharge. If the vehicle is returned with a fuel level higher than at delivery, no amount will be paid for the difference.',
        'The vehicle is returned in the same state of cleanliness in which it was delivered. When the vehicle is returned in extraordinary dirty conditions (vomit, mud, sand, animal hair, organic remains, persistent bad smell, unusual stains, residues in upholstery) the LESSOR may charge the RENTER the extraordinary cleaning costs, with a minimum equivalent to one hour of professional detailing service.',
        'The RENTER undertakes to periodically check oil, coolant and brake-fluid levels and tyre pressure, and to heed the instrument panel warnings, assuming the costs derived from negligent use of the vehicle (including refuelling with the wrong fuel).'
      ]
    },
    ro: {
      title: '6. COMBUSTIBIL, CURĂȚENIE ȘI ÎNTREȚINERE',
      body: [
        'Vehiculul se predă cu nivelul de combustibil consemnat și fotografiat în procesul-verbal de predare și trebuie returnat cu același nivel, care se verifică și se consemnează în procesul-verbal de returnare. Dacă nivelul la returnare este mai mic, se va percepe realimentarea la prețul în vigoare la momentul returnării plus un supliment de gestionare. Dacă vehiculul se returnează cu un nivel de combustibil mai mare decât la predare, nu se va plăti nicio sumă pentru diferență.',
        'Vehiculul se returnează în aceeași stare de curățenie în care a fost predat. Când vehiculul se returnează în condiții de murdărie extraordinară (vărsături, noroi, nisip, păr de animale, resturi organice, miros persistent neplăcut, pete neobișnuite, reziduuri în tapițerie) LOCATORUL poate percepe LOCATARULUI costurile de curățenie extraordinară, cu un minim echivalent cu o oră de serviciu profesional de detailing.',
        'LOCATARUL se obligă să verifice periodic nivelurile de ulei, lichid de răcire, lichid de frână și presiunea pneurilor, și să respecte indicațiile tabloului de bord, asumându-și cheltuielile derivate din folosința neglijentă a vehiculului (inclusiv realimentarea cu combustibil necorespunzător).'
      ]
    }
  },
  legal_use: {
    es: {
      title: '7. USO LEGAL DEL VEHÍCULO Y COLABORACIÓN CON LAS AUTORIDADES',
      body: [
        'El ARRENDATARIO declara que utilizará el vehículo exclusivamente para fines lícitos y de conformidad con la legislación española y europea vigente. Está expresamente prohibido: (i) transportar personas o mercancías con infracción de la ley; (ii) participar en competiciones, rallies, pruebas deportivas o cualquier uso en circuito; (iii) empujar o remolcar otros vehículos; (iv) utilizar el vehículo para la comisión de actos ilícitos; (v) circular fuera de carreteras pavimentadas o en condiciones no aptas para el vehículo; (vi) ceder, subarrendar o prestar el vehículo a terceros distintos de los conductores expresamente declarados en este contrato; (vii) conducir bajo los efectos del alcohol, drogas o sustancias que alteren la capacidad de conducción, o superar los límites legales de alcoholemia; (viii) fumar en el interior del vehículo; (ix) transportar animales sin transportín adecuado.',
        'El ARRENDATARIO será el único responsable de cualquier uso indebido, ilícito o contrario a la normativa aplicable realizado durante el período de alquiler, exonerando expresamente al ARRENDADOR de cualquier responsabilidad administrativa, civil o penal derivada de dichos actos, incluido el pago de fianzas en procedimientos penales en los que el ARRENDADOR pudiera personarse como perjudicado.',
        'El ARRENDATARIO autoriza expresamente al ARRENDADOR a facilitar sus datos personales identificativos, copia del presente contrato, copia del permiso de conducir, fotografías de la entrega y devolución del vehículo, y cualquier otra documentación relacionada con el alquiler, a la Dirección General de Tráfico (DGT), a los ayuntamientos y demás autoridades administrativas competentes para la identificación del conductor, la atribución de sanciones de tráfico, la gestión de Zonas de Bajas Emisiones (ZBE) y de Zona SER, así como a las Fuerzas y Cuerpos de Seguridad del Estado (Guardia Civil, Policía Nacional, Policías Autonómicas y Policías Locales), a los Juzgados y Tribunales y a las compañías aseguradoras, cuando resulte necesario para la identificación del conductor, la persecución de infracciones, la recuperación del vehículo, la instrucción de diligencias penales o la atención de cualquier requerimiento legal.',
        'Esta comunicación de datos no se basa en el consentimiento del ARRENDATARIO, sino en el cumplimiento de obligaciones legales del ARRENDADOR y en su interés legítimo (artículos 6.1.c) y 6.1.f) del Reglamento (UE) 2016/679 y artículos 6 y 8 de la Ley Orgánica 3/2018), en particular el deber de identificar al conductor previsto en la normativa de tráfico. Por ello se realiza con independencia de la voluntad del ARRENDATARIO, sin perjuicio de los derechos que le reconoce la cláusula de protección de datos de este contrato.'
      ]
    },
    en: {
      title: '7. LAWFUL USE OF THE VEHICLE AND COOPERATION WITH AUTHORITIES',
      body: [
        'The RENTER declares that they will use the vehicle exclusively for lawful purposes and in accordance with current Spanish and European legislation. The following are expressly prohibited: (i) transporting persons or goods in violation of the law; (ii) taking part in competitions, rallies, sporting events or any use on a circuit; (iii) pushing or towing other vehicles; (iv) using the vehicle for the commission of unlawful acts; (v) driving off paved roads or in conditions unsuitable for the vehicle; (vi) assigning, subletting or lending the vehicle to third parties other than the drivers expressly declared in this contract; (vii) driving under the influence of alcohol, drugs or substances that impair driving ability, or exceeding the legal alcohol limits; (viii) smoking inside the vehicle; (ix) transporting animals without a suitable carrier.',
        'The RENTER shall be the sole responsible party for any improper, illicit or unlawful use of the vehicle during the rental period, expressly holding the LESSOR harmless from any administrative, civil or criminal liability arising from such acts, including the payment of any bail in criminal proceedings in which the LESSOR may appear as injured party.',
        'The RENTER expressly authorises the LESSOR to disclose their personal identification data, a copy of this contract, a copy of the driving licence, photographs of the delivery and return of the vehicle, and any other documentation related to the rental, to the Dirección General de Tráfico (DGT), to the city councils and other competent administrative authorities for driver identification, attribution of traffic sanctions, management of Low Emission Zones (ZBE) and SER Zone, as well as to the Security Forces and Corps (Guardia Civil, National Police, regional and local police), to the Courts and Tribunals and to insurance companies, when necessary for driver identification, prosecution of offences, recovery of the vehicle, criminal proceedings or any other legal requirement.',
        'This disclosure is not based on the RENTER\'s consent, but on the LESSOR\'s compliance with legal obligations and on its legitimate interest (articles 6.1.c) and 6.1.f) of Regulation (EU) 2016/679 and articles 6 and 8 of Spanish Organic Law 3/2018), in particular the duty to identify the driver laid down in road traffic legislation. It therefore takes place regardless of the RENTER\'s wishes, without prejudice to the rights granted to them under the data protection clause of this contract.'
      ]
    },
    ro: {
      title: '7. FOLOSINȚA LEGALĂ A VEHICULULUI ȘI COOPERAREA CU AUTORITĂȚILE',
      body: [
        'LOCATARUL declară că va folosi vehiculul exclusiv în scopuri legale și în conformitate cu legislația spaniolă și europeană în vigoare. Sunt interzise în mod expres: (i) transportul de persoane sau mărfuri cu încălcarea legii; (ii) participarea la competiții, raliuri, probe sportive sau orice folosință pe circuit; (iii) împingerea sau tractarea altor vehicule; (iv) utilizarea vehiculului pentru săvârșirea de acte ilicite; (v) conducerea în afara drumurilor pavate sau în condiții nepotrivite pentru vehicul; (vi) cedarea, subînchirierea sau împrumutarea vehiculului către terți, alții decât conducătorii declarați în mod expres în acest contract; (vii) conducerea sub influența alcoolului, drogurilor sau a substanțelor care alterează capacitatea de conducere, sau depășirea limitelor legale de alcoolemie; (viii) fumatul în interiorul vehiculului; (ix) transportul animalelor fără cușcă adecvată.',
        'LOCATARUL va fi singurul responsabil pentru orice folosință necorespunzătoare, ilicită sau contrară normelor aplicabile realizată în perioada închirierii, exonorând în mod expres LOCATORUL de orice răspundere administrativă, civilă sau penală derivată din aceste acte, inclusiv plata cauțiunilor în procedurile penale în care LOCATORUL ar putea constitui parte civilă.',
        'LOCATARUL autorizează în mod expres LOCATORUL să furnizeze datele sale personale de identificare, o copie a prezentului contract, o copie a permisului de conducere, fotografii ale predării și returnării vehiculului și orice altă documentație legată de închiriere, către Dirección General de Tráfico (DGT), către primării și alte autorități administrative competente pentru identificarea conducătorului, atribuirea sancțiunilor de circulație, gestionarea Zonelor cu Emisii Reduse (ZBE) și a Zonei SER, precum și către Forțele și Corpurile de Securitate (Guardia Civil, Poliția Națională, poliții regionale și locale), către Instanțele Judecătorești și către companiile de asigurări, când este necesar pentru identificarea conducătorului, urmărirea contravențiilor, recuperarea vehiculului, instruirea de diligențe penale sau pentru a răspunde oricărei cerințe legale.',
        'Această comunicare de date nu se bazează pe consimțământul LOCATARULUI, ci pe îndeplinirea obligațiilor legale ale LOCATORULUI și pe interesul său legitim (articolele 6.1.c) și 6.1.f) din Regulamentul (UE) 2016/679 și articolele 6 și 8 din Legea Organică spaniolă 3/2018), în special obligația de a identifica conducătorul prevăzută de legislația rutieră. Prin urmare, se efectuează independent de voința LOCATARULUI, fără a aduce atingere drepturilor recunoscute acestuia în clauza de protecție a datelor din prezentul contract.'
      ]
    }
  },
  geographic_limits: {
    es: {
      title: '8. ÁMBITO GEOGRÁFICO',
      body: [
        'El vehículo podrá ser conducido dentro del territorio de España (Península, Baleares, Ceuta y Melilla). Para desplazamientos a Canarias, Andorra, Gibraltar, Marruecos o cualquier otro país distinto de España, el ARRENDATARIO deberá obtener autorización previa, expresa y por escrito del ARRENDADOR, que podrá requerir la suscripción de un seguro de frontera o equivalente.',
        'La conducción del vehículo fuera del ámbito geográfico autorizado sin consentimiento escrito del ARRENDADOR se considera incumplimiento grave, dejando sin efecto todas las coberturas y dejando al ARRENDATARIO como único responsable de cuantos daños, sanciones, decomisos o gastos se deriven, incluidos los de repatriación del vehículo.'
      ]
    },
    en: {
      title: '8. GEOGRAPHICAL SCOPE',
      body: [
        'The vehicle may be driven within the territory of Spain (mainland, Balearic Islands, Ceuta and Melilla). For journeys to the Canary Islands, Andorra, Gibraltar, Morocco or any other country other than Spain, the RENTER must obtain prior, express, written authorisation from the LESSOR, which may require taking out a frontier-insurance policy or equivalent.',
        'Driving the vehicle outside the authorised geographical area without written consent of the LESSOR is considered a serious breach, voiding all coverages and leaving the RENTER as sole responsible party for any damage, sanctions, confiscations or costs, including repatriation of the vehicle.'
      ]
    },
    ro: {
      title: '8. SFERA GEOGRAFICĂ',
      body: [
        'Vehiculul poate fi condus pe teritoriul Spaniei (peninsulă, Baleare, Ceuta și Melilla). Pentru deplasări în Canare, Andorra, Gibraltar, Maroc sau orice altă țară diferită de Spania, LOCATARUL trebuie să obțină autorizație prealabilă, expresă și scrisă a LOCATORULUI, care poate solicita încheierea unei polițe de asigurare de frontieră sau echivalentă.',
        'Conducerea vehiculului în afara sferei geografice autorizate fără consimțământul scris al LOCATORULUI este considerată încălcare gravă, anulând toate acoperirile și lăsând LOCATARUL ca unic responsabil pentru toate daunele, sancțiunile, confiscările sau cheltuielile derivate, inclusiv repatrierea vehiculului.'
      ]
    }
  },
  fines_penalties: {
    es: {
      title: '9. MULTAS, SANCIONES, PEAJES Y GASTOS DE GESTIÓN',
      body: [
        'El ARRENDATARIO será el único responsable de todas las multas, sanciones, denuncias, peajes, gastos de estacionamiento, accesos a ZBE, retirada por grúa y cualquier otra obligación económica derivada del uso del vehículo durante el período de alquiler.',
        'Serán igualmente por cuenta exclusiva del ARRENDATARIO los gastos de gestión administrativa en que incurra el ARRENDADOR como consecuencia de multas, sanciones o peajes a él repercutidos, con un mínimo de 30 € por expediente, así como el coste de los servicios de grúa, rescate, repatriación del vehículo, apertura del vehículo por pérdida de llaves y sustitución de cerraduras.',
        'El ARRENDADOR repercutirá al ARRENDATARIO el importe íntegro de cualquier multa, sanción o peaje, incluidos los recargos y los intereses de demora, mediante cargo en la tarjeta facilitada en garantía o, en su defecto, mediante acción de reclamación de cantidad, todo ello sin perjuicio de su derecho a suministrar a la autoridad sancionadora los datos identificativos del conductor conforme a lo previsto en la cláusula de uso legal del vehículo y colaboración con las autoridades.'
      ]
    },
    en: {
      title: '9. FINES, SANCTIONS, TOLLS AND ADMINISTRATIVE COSTS',
      body: [
        'The RENTER shall be the sole responsible party for all fines, sanctions, complaints, tolls, parking costs, ZBE access charges, tow-away fees and any other economic obligation derived from the use of the vehicle during the rental period.',
        'The RENTER shall also be exclusively responsible for the administrative handling costs incurred by the LESSOR as a consequence of fines, sanctions or tolls passed on to it, with a minimum of 30 € per file, as well as the cost of tow, rescue, repatriation of the vehicle, vehicle opening for lost keys and lock replacement.',
        'The LESSOR will pass on to the RENTER the full amount of any fine, sanction or toll, including surcharges and late-payment interest, by charging it to the card provided as guarantee or, failing that, by bringing a claim for the amount, all without prejudice to its right to provide the sanctioning authority with the identification data of the driver as foreseen in the clause on lawful use of the vehicle and cooperation with authorities.'
      ]
    },
    ro: {
      title: '9. AMENZI, SANCȚIUNI, TAXE DE AUTOSTRADĂ ȘI COSTURI ADMINISTRATIVE',
      body: [
        'LOCATARUL va fi singurul responsabil pentru toate amenzile, sancțiunile, reclamațiile, taxele de autostradă, cheltuielile de parcare, taxele de acces ZBE, taxele de ridicare cu platformă și orice altă obligație economică derivată din folosința vehiculului în perioada închirierii.',
        'Vor fi de asemenea în sarcina exclusivă a LOCATARULUI cheltuielile de gestionare administrativă în care LOCATORUL va suporta ca urmare a amenzilor, sancțiunilor sau taxelor de autostradă care îi sunt imputate, cu un minim de 30 € per dosar, precum și costul serviciilor de platformă, salvare, repatriere a vehiculului, deschiderea vehiculului pentru chei pierdute și înlocuirea încuietorilor.',
        'LOCATORUL va imputa LOCATARULUI suma integrală a oricărei amenzi, sancțiuni sau taxe de autostradă, inclusiv suprataxele și dobânzile de întârziere, prin debitarea cardului furnizat ca garanție sau, în lipsă, prin acțiune de recuperare a sumei, totul fără a aduce atingere dreptului său de a furniza autorității sancționatoare datele de identificare ale conducătorului conform celor prevăzute în clauza privind folosința legală a vehiculului și cooperarea cu autoritățile.'
      ]
    }
  },
  damages_intentional: {
    es: {
      title: '10. DAÑOS AL VEHÍCULO, VANDALISMO Y ACTOS DELIBERADOS',
      body: [
        'El ARRENDATARIO será responsable de los daños causados al vehículo por uso negligente, conducción temeraria, incumplimiento de las normas de circulación, utilización indebida del vehículo, o por cualquier otro tipo de actuación culposa. El importe a abonar se determinará por peritación del taller designado por el ARRENDADOR o, en su caso, por la aseguradora, y se cargará de la fianza o, si esta fuere insuficiente, se reclamará por la vía correspondiente.',
        'En particular, el ARRENDATARIO será responsable del coste íntegro de la reparación de cualesquiera daños que se determinen como consecuencia de actos deliberados de vandalismo, entendido como toda acción intencionada de dañar, romper, rayar, manchar, mutilar, golpear, pintar, vaciar o inutilizar el vehículo, sus componentes, accesorios o elementos interiores o exteriores, así como los causados a propósito por terceros introducidos en el vehículo por el ARRENDATARIO, sin perjuicio de la responsabilidad penal que pudiera derivarse de conformidad con los artículos 263 y 264 del Código Penal (delito de daños), que contempla penas de prisión de uno a tres años para daños graves causados por cualquier medio, incluidas las pintadas o inscripciones, y de hasta un año de prisión cuando el valor del daño supere los 400 €.',
        'Cuando el ARRENDATARIO tenga conocimiento de cualquier daño, intento de robo, robo, vandalismo, acto vandálico, vandalismo intencionado, destrozo o cualquier deterioro del vehículo, ocurrido tanto dentro como fuera de su presencia, queda obligado a: (i) denunciarlo inmediatamente ante las Fuerzas y Cuerpos de Seguridad (Guardia Civil, Policía Nacional o Policía Local), obteniendo copia de la denuncia con número de referencia; (ii) informar al ARRENDADOR en el plazo máximo de dos (2) horas mediante llamada telefónica al número indicado en la cabecera, facilitando copia de la denuncia; (iii) no mover el vehículo hasta la llegada del personal del ARRENDADOR o, en su caso, de las autoridades. La omisión de esta obligación de denuncia facultará al ARRENDADOR para considerar al ARRENDATARIO como único responsable de los daños, anulando cualquier cobertura.'
      ]
    },
    en: {
      title: '10. VEHICLE DAMAGE, VANDALISM AND DELIBERATE ACTS',
      body: [
        'The RENTER shall be liable for damage to the vehicle caused by negligent use, reckless driving, breach of traffic rules, improper use of the vehicle, or any other culpable action. The amount payable will be determined by the workshop appointed by the LESSOR or, if applicable, by the insurer, and will be charged against the deposit or, if insufficient, will be claimed through the appropriate channels.',
        'In particular, the RENTER shall be liable for the full cost of repairing any damage determined to be the result of deliberate acts of vandalism, understood as any intentional action to damage, break, scratch, stain, mutilate, hit, paint, empty or disable the vehicle, its components, accessories or interior or exterior elements, as well as that caused intentionally by third parties introduced into the vehicle by the RENTER, without prejudice to the criminal liability that may be derived from articles 263 and 264 of the Spanish Criminal Code (damage offence), which provides for prison sentences of one to three years for serious damage caused by any means, including graffiti or inscriptions, and of up to one year in prison when the value of the damage exceeds 400 €.',
        'When the RENTER becomes aware of any damage, attempted theft, theft, vandalism, vandalism, intentional vandalism, destruction or any other deterioration of the vehicle, occurring both inside and outside their presence, they are obliged to: (i) report it immediately to the Security Forces and Corps (Guardia Civil, National Police or Local Police), obtaining a copy of the report with a reference number; (ii) inform the LESSOR within a maximum of two (2) hours by calling the number indicated in the header, providing a copy of the report; (iii) not move the vehicle until the LESSOR\'s personnel or, if applicable, the authorities arrive. Failure to comply with this reporting obligation will empower the LESSOR to consider the RENTER as the sole responsible party for the damage, voiding any coverage.'
      ]
    },
    ro: {
      title: '10. DAUNE ADUSE VEHICULULUI, VANDALISM ȘI ACTE DELIBERATE',
      body: [
        'LOCATARUL va fi responsabil pentru daunele cauzate vehiculului prin folosință neglijentă, conducere temerară, încălcarea normelor de circulație, utilizarea necorespunzătoare a vehiculului sau prin orice alt tip de acțiune culpabilă. Suma de plată se va stabili prin expertiza atelierului desemnat de LOCATOR sau, dacă este cazul, de către asigurator, și se va debita din garanție sau, dacă aceasta este insuficientă, se va recupera pe calea corespunzătoare.',
        'În special, LOCATARUL va fi responsabil pentru costul integral al reparării oricăror daune care se stabilesc ca fiind consecința unor acte deliberate de vandalism, înțeles ca orice acțiune intenționată de a deteriora, rupe, zgâria, păta, mutila, lovi, picta, goli sau face inutilizabil vehiculul, componentele, accesoriile sau elementele sale interioare sau exterioare, precum și cele cauzate cu intenție de terțe persoane introduse în vehicul de către LOCATAR, fără a aduce atingere răspunderii penale care ar putea decurge din articolele 263 și 264 din Codul Penal spaniol (infracțiunea de daune), care prevede pedepse cu închisoarea de la unu la trei ani pentru daune grave cauzate prin orice mijloc, inclusiv graffiti sau inscripții, și de până la un an de închisoare când valoarea daunei depășește 400 €.',
        'Când LOCATARUL ia cunoștință de orice daună, tentativă de furt, furt, vandalism, vandalism intenționat, distrugere sau orice altă deteriorare a vehiculului, produsă atât în prezența cât și în absența sa, este obligat: (i) să o denunțe imediat Forțelor și Corpurilor de Securitate (Guardia Civil, Poliția Națională sau Poliția Locală), obținând o copie a denunțului cu număr de referință; (ii) să informeze LOCATORUL în termen de maximum două (2) ore prin apel telefonic la numărul indicat în antet, furnizând o copie a denunțului; (iii) să nu miște vehiculul până la sosirea personalului LOCATORULUI sau, după caz, a autorităților. Omisiunea acestei obligații de denunțare va îndreptăți LOCATORUL să considere LOCATARUL ca unic responsabil pentru daune, anulând orice acoperire.'
      ]
    }
  },
  theft_unreturned: {
    es: {
      title: '11. NO DEVOLUCIÓN, SUSTRACCIÓN Y APROPIACIÓN INDEBIDA',
      body: [
        'El ARRENDATARIO se obliga a devolver el vehículo, sus llaves, documentos y accesorios en la fecha, hora y lugar pactados. La retención del vehículo más allá del plazo contractual constituye un incumplimiento grave que puede ser constitutivo de delito, dando lugar a las responsabilidades civiles y, en su caso, penales que correspondan, en particular las previstas en los artículos 237 a 243 del Código Penal (sustracción), 244 del Código Penal (utilización ilegítima de vehículo ajeno) y 252 y siguientes del Código Penal (apropiación indebida y alzamiento de bienes).',
        'En caso de no devolución en la fecha pactada, el ARRENDADOR queda expresamente facultado para: (a) requerir al ARRENDATARIO la devolución inmediata del vehículo por cualquier medio, incluidos los telemáticos (localizador GPS); (b) formular denuncia ante las Fuerzas y Cuerpos de Seguridad, en particular ante la Guardia Civil, por los delitos de retención indebida, sustracción, apropiación indebida o, en su caso, estafa; (c) ejercitar las acciones civiles de reclamación del valor del vehículo, los daños y perjuicios y el lucro cesante; y (d) publicar los hechos a través de los medios que considere oportunos para la recuperación del vehículo.',
        'El ARRENDATARIO exonera expresamente al ARRENDADOR de cualquier responsabilidad que pudiera derivarse de la inmovilización o retirada del vehículo por las autoridades o por terceros, en caso de no devolución o de estacionamiento indebido al término del contrato.'
      ]
    },
    en: {
      title: '11. FAILURE TO RETURN, THEFT AND MISAPPROPRIATION',
      body: [
        'The RENTER undertakes to return the vehicle, its keys, documents and accessories on the date, time and at the place agreed. Retention of the vehicle beyond the contractual term constitutes a serious breach that may constitute a criminal offence, giving rise to civil and, where applicable, criminal liabilities, in particular those provided for in articles 237 to 243 of the Spanish Criminal Code (theft), 244 of the Spanish Criminal Code (unlawful use of another\'s vehicle) and 252 and following of the Spanish Criminal Code (misappropriation and removal of assets).',
        'In the event of non-return on the agreed date, the LESSOR is expressly empowered to: (a) require the RENTER to return the vehicle immediately by any means, including telematic (GPS locator); (b) file a complaint with the Security Forces and Corps, in particular with the Guardia Civil, for the offences of unlawful retention, theft, misappropriation or, if applicable, fraud; (c) bring civil actions for the value of the vehicle, damages and lost profits; and (d) publish the facts through whatever means it considers appropriate for the recovery of the vehicle.',
        'The RENTER expressly holds the LESSOR harmless from any liability that may arise from the immobilisation or removal of the vehicle by the authorities or by third parties, in the event of non-return or improper parking at the end of the contract.'
      ]
    },
    ro: {
      title: '11. NERETURNAREA, FURTUL ȘI ÎNSUȘIREA INDEBITĂ',
      body: [
        'LOCATARUL se obligă să returneze vehiculul, cheile, documentele și accesoriile la data, ora și locul convenite. Reținerea vehiculului peste termenul contractual constituie o încălcare gravă care poate fi constitutivă de infracțiune, generând răspunderea civilă și, după caz, penală corespunzătoare, în special cele prevăzute la articolele 237-243 din Codul Penal spaniol (furt), 244 din Codul Penal spaniol (folosința nelegitimă a vehiculului altuia) și 252 și următoarele din Codul Penal spaniol (însușire nedatorată și ridicare de bunuri).',
        'În caz de nereturnare la data convenită, LOCATORUL este împuternicit în mod expres: (a) să solicite LOCATARULUI returnarea imediată a vehiculului prin orice mijloace, inclusiv telematice (localizator GPS); (b) să formuleze plângere la Forțele și Corpurile de Securitate, în special la Guardia Civil, pentru infracțiunile de reținere neîntemeiată, sustragere, însușire nedatorată sau, dacă este cazul, înșelăciune; (c) să exercite acțiunile civile de recuperare a valorii vehiculului, daune și pierderi de profit; și (d) să publice faptele prin mijloacele pe care le consideră oportune pentru recuperarea vehiculului.',
        'LOCATARUL exonerează în mod expres LOCATORUL de orice răspundere care ar putea decurge din imobilizarea sau ridicarea vehiculului de către autorități sau de către terți, în caz de nereturnare sau de parcare necorespunzătoare la sfârșitul contractului.'
      ]
    }
  },
  incidents: {
    es: {
      title: '12. ACCIDENTES, AVERÍAS Y ASISTENCIA',
      body: [
        'En caso de accidente, robo, hurto, incendio, vandalismo o cualquier otra incidencia, el ARRENDATARIO deberá: (i) obtener parte de accidente firmado por ambas partes si hay terceros; (ii) denunciar el hecho ante las Fuerzas y Cuerpos de Seguridad competentes, obteniendo copia de la denuncia; (iii) no mover el vehículo hasta que se persone el personal del ARRENDADOR o las autoridades; (iv) comunicar el hecho al ARRENDADOR en el plazo máximo de dos (2) horas; (v) cumplimentar el parte amistoso de accidentes en los impresos disponibles en el vehículo. La omisión de la denuncia o de la comunicación facultará al ARRENDADOR para considerar al ARRENDATARIO como responsable de la totalidad de los daños.',
        'El vehículo cuenta con una póliza de seguro con cobertura de responsabilidad civil obligatoria frente a terceros, conforme al Real Decreto Legislativo 8/2004, sobre responsabilidad civil y seguro en la circulación de vehículos a motor. La identificación de la compañía aseguradora, el número de póliza y el teléfono de asistencia en carretera constan en la sección "Datos del vehículo" de este contrato. Las coberturas adicionales (seguro a todo riesgo con o sin franquicia, seguro de ocupantes, etc.) sólo serán aplicables si han sido expresamente contratadas y abonadas por el ARRENDATARIO, según se refleja en la sección "Precio y fianza".',
        'La asistencia en carretera derivada de avería mecánica no imputable al ARRENDATARIO (defectos de fabricación, desgaste normal) está incluida en el seguro obligatorio. La asistencia derivada de uso negligente, repostaje incorrecto, pérdida de llaves, robo o cualesquiera otras causas imputables al ARRENDATARIO será a su cargo, incluidos los gastos de grúa, repatriación del vehículo, sustitución de cerraduras y noches de hotel si procede.'
      ]
    },
    en: {
      title: '12. ACCIDENTS, BREAKDOWNS AND ASSISTANCE',
      body: [
        'In the event of an accident, theft, robbery, fire, vandalism or any other incident, the RENTER must: (i) obtain an accident report signed by both parties if there are third parties; (ii) report the event to the competent Security Forces and Corps, obtaining a copy of the report; (iii) not move the vehicle until the LESSOR\'s personnel or the authorities arrive; (iv) report the event to the LESSOR within a maximum of two (2) hours; (v) fill in the amicable accident form on the printed forms available in the vehicle. Failure to report or to inform will empower the LESSOR to consider the RENTER responsible for the totality of the damage.',
        'The vehicle is covered by an insurance policy with mandatory third-party liability cover, in accordance with Royal Legislative Decree 8/2004, on civil liability and insurance in vehicle traffic. The identification of the insurance company, the policy number and the road-assistance telephone number are shown in the "Vehicle data" section. Additional coverages (fully comprehensive insurance with or without deductible, occupant insurance, etc.) will only apply if expressly contracted and paid for by the RENTER, as reflected in the "Price and deposit" section.',
        'Road assistance derived from mechanical failure not attributable to the RENTER (manufacturing defects, normal wear) is included in the mandatory insurance. Assistance derived from negligent use, incorrect refuelling, loss of keys, theft or any other causes attributable to the RENTER will be at their expense, including tow, repatriation of the vehicle, replacement of locks and hotel nights if applicable.'
      ]
    },
    ro: {
      title: '12. ACCIDENTE, DEFECȚIUNI ȘI ASISTENȚĂ',
      body: [
        'În caz de accident, furt, tâlhărie, incendiu, vandalism sau orice alt incident, LOCATARUL trebuie: (i) să obțină un proces-verbal de accident semnat de ambele părți dacă există terți; (ii) să denunțe fapta la Forțele și Corpurile de Securitate competente, obținând o copie a denunțului; (iii) să nu miște vehiculul până la sosirea personalului LOCATORULUI sau a autorităților; (iv) să comunice fapta LOCATORULUI în termen de maximum două (2) ore; (v) să completeze formularul de accident amiabil pe tipizatele disponibile în vehicul. Omisiunea denunțului sau a comunicării va îndreptăți LOCATORUL să considere LOCATARUL responsabil pentru totalitatea daunelor.',
        'Vehiculul este acoperit de o poliță de asigurare cu acoperire de răspundere civilă obligatorie față de terți, conform Decretului legislativ regal 8/2004, privind răspunderea civilă și asigurarea în circulația vehiculelor. Identificarea companiei de asigurări, numărul poliței și telefonul de asistență rutieră sunt indicate în secțiunea "Datele vehiculului". Acoperirile suplimentare (asigurare casco cu sau fără franciză, asigurare de ocupanți etc.) se vor aplica doar dacă au fost contractate și plătite în mod expres de către LOCATAR, conform celor reflectate în secțiunea "Preț și garanție".',
        'Asistența rutieră derivată din defecțiune mecanică neimputabilă LOCATARULUI (defecte de fabricație, uzură normală) este inclusă în asigurarea obligatorie. Asistența derivată din folosința neglijentă, realimentarea incorectă, pierderea cheilor, furtul sau orice alte cauze imputabile LOCATARULUI va fi în sarcina acestuia, inclusiv cheltuielile de platformă, repatrierea vehiculului, înlocuirea încuietorilor și nopți de hotel dacă este cazul.'
      ]
    }
  },
  insurance: {
    es: {
      title: '13. SEGURO Y COBERTURAS',
      body: [
        'La póliza de seguro del vehículo cubre, como mínimo, la responsabilidad civil obligatoria frente a terceros prevista en la legislación española. La compañía aseguradora, el número de póliza y el teléfono de asistencia en carretera se indican en la sección "Datos del vehículo" del presente contrato.',
        'Quedan expresamente excluidos de toda cobertura, salvo pacto en contrario y pago de la prima adicional correspondiente, los daños derivados de: (a) conducir bajo los efectos del alcohol, drogas o sustancias psicotrópicas; (b) conducir sin el permiso adecuado o con el permiso suspendido, retirado o caducado; (c) utilizar el vehículo en actividades ilícitas o fuera de las vías públicas autorizadas; (d) transportar personas o mercancías infringiendo la ley; (e) cesión del vehículo a persona no autorizada; (f) abandonar el vehículo en lugar no permitido; (g) transportar más pasajeros de los autorizados por la ficha técnica del vehículo; (h) cualquier otra causa de exclusión prevista en la Ley de Contrato de Seguro o en las condiciones generales y particulares de la póliza.',
        'El ARRENDATARIO podrá contratar voluntariamente coberturas adicionales (seguro a todo riesgo con o sin franquicia, seguro de ocupantes, ampliación de kilometraje, conductor adicional, etc.) en las condiciones y precios vigentes al inicio del alquiler, que se reflejarán en la sección "Precio y fianza".'
      ]
    },
    en: {
      title: '13. INSURANCE AND COVERAGES',
      body: [
        'The vehicle\'s insurance policy covers, at a minimum, the mandatory third-party liability cover required by Spanish law. The insurance company, the policy number and the road-assistance telephone number are indicated in the "Vehicle data" section of this contract.',
        'The following are expressly excluded from all coverages, unless otherwise agreed and the corresponding additional premium is paid, damage arising from: (a) driving under the influence of alcohol, drugs or psychotropic substances; (b) driving without the appropriate licence or with the licence suspended, withdrawn or expired; (c) using the vehicle in illicit activities or outside the authorised public roads; (d) transporting persons or goods in violation of the law; (e) assigning the vehicle to an unauthorised person; (f) abandoning the vehicle in a place not allowed; (g) transporting more passengers than authorised by the vehicle\'s technical sheet; (h) any other cause of exclusion foreseen in the Insurance Contract Act or in the general and particular conditions of the policy.',
        'The RENTER may voluntarily take out additional coverages (fully comprehensive insurance with or without deductible, occupant insurance, mileage extension, additional driver, etc.) in the conditions and prices in force at the start of the rental, which will be reflected in the "Price and deposit" section.'
      ]
    },
    ro: {
      title: '13. ASIGURARE ȘI ACOPERIRI',
      body: [
        'Polița de asigurare a vehiculului acoperă, ca minim, acoperirea de răspundere civilă obligatorie față de terți prevăzută de legislația spaniolă. Compania de asigurări, numărul poliței și telefonul de asistență rutieră sunt indicate în secțiunea "Datele vehiculului" a prezentului contract.',
        'Sunt excluse în mod expres din toate acoperirile, dacă nu se convine altfel și nu se plătește prima suplimentară corespunzătoare, daunele derivate din: (a) conducerea sub influența alcoolului, drogurilor sau a substanțelor psihotrope; (b) conducerea fără permisul corespunzător sau cu permisul suspendat, retras sau expirat; (c) utilizarea vehiculului în activități ilicite sau în afara drumurilor publice autorizate; (d) transportul de persoane sau mărfuri cu încălcarea legii; (e) cedarea vehiculului unei persoane neautorizate; (f) abandonarea vehiculului într-un loc nepermis; (g) transportul a mai mulți pasageri decât cei autorizați de fișa tehnică a vehiculului; (h) orice altă cauză de excludere prevăzută în Legea Contractului de Asigurare sau în condițiile generale și particulare ale poliței.',
        'LOCATARUL poate contracta voluntar acoperiri suplimentare (asigurare casco cu sau fără franciză, asigurare de ocupanți, extensie de kilometraj, conducător suplimentar etc.) în condițiile și prețurile în vigoare la începutul închirierii, care se vor reflecta în secțiunea "Preț și garanție".'
      ]
    }
  },
  data_protection: {
    es: {
      title: '14. PROTECCIÓN DE DATOS PERSONALES (LOPDGDD / RGPD)',
      body: [
        'En cumplimiento del Reglamento (UE) 2016/679 (RGPD) y de la Ley Orgánica 3/2018 (LOPDGDD), el ARRENDATARIO queda informado de que los datos personales facilitados en este contrato, así como los generados durante su ejecución (kilometraje, nivel de combustible, fotografías del estado del vehículo, partes de accidente y demás datos derivados del uso del vehículo), serán tratados por el ARRENDADOR, responsable del tratamiento, con las finalidades y bases jurídicas siguientes: (a) la gestión integral del contrato de alquiler y la facturación, sobre la base de la ejecución del contrato (art. 6.1.b RGPD); (b) el cumplimiento de obligaciones legales, fiscales, contables y mercantiles, y la identificación del conductor ante las autoridades administrativas y judiciales, sobre la base de una obligación legal (art. 6.1.c RGPD); (c) el mantenimiento del histórico de clientes, la reclamación extrajudicial y judicial de las cantidades adeudadas, la prevención del fraude y la seguridad del vehículo y de sus ocupantes, sobre la base del interés legítimo del ARRENDADOR (art. 6.1.f RGPD).',
        'GEOLOCALIZACIÓN DEL VEHÍCULO. El ARRENDATARIO queda expresamente informado de que el vehículo está equipado con un dispositivo de localización por GPS que permite conocer su posición durante el período de alquiler. Esta información se trata sobre la base del interés legítimo del ARRENDADOR (art. 6.1.f RGPD) y con las siguientes finalidades exclusivas: prevenir y recuperar el vehículo en caso de robo, hurto o no devolución; verificar el cumplimiento del ámbito geográfico autorizado; y atender los requerimientos de las autoridades. Los datos de localización no se utilizan para evaluar la conducción ni con fines comerciales, y se conservan únicamente durante el tiempo necesario para dichas finalidades.',
        'El responsable del tratamiento es la Sociedad identificada en la cabecera. Los datos se conservarán mientras se mantenga la relación contractual y, posteriormente, durante el plazo de prescripción de las acciones legales derivadas. El ARRENDATARIO puede ejercer en cualquier momento sus derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento, portabilidad y a no ser objeto de decisiones automatizadas con efectos jurídicos, mediante comunicación escrita dirigida al ARRENDADOR a la dirección indicada en la cabecera, acompañando copia de un documento de identidad. El ARRENDATARIO queda informado de su derecho a presentar una reclamación ante la Agencia Española de Protección de Datos (www.aepd.es) si considera infringidos sus derechos.'
      ]
    },
    en: {
      title: '14. PERSONAL DATA PROTECTION (GDPR / LOPDGDD)',
      body: [
        'In compliance with Regulation (EU) 2016/679 (GDPR) and Spanish Organic Law 3/2018 (LOPDGDD), the RENTER is informed that the personal data provided in this contract, as well as those generated during its performance (mileage, fuel level, photographs of the vehicle condition, accident reports and other data arising from the use of the vehicle), will be processed by the LESSOR, as data controller, for the following purposes and on the following legal bases: (a) full management of the rental contract and invoicing, on the basis of performance of the contract (art. 6.1.b GDPR); (b) compliance with legal, tax, accounting and commercial obligations, and identification of the driver before administrative and judicial authorities, on the basis of a legal obligation (art. 6.1.c GDPR); (c) maintenance of the customer history, out-of-court and judicial claims for amounts owed, fraud prevention and the safety of the vehicle and its occupants, on the basis of the legitimate interest of the LESSOR (art. 6.1.f GDPR).',
        'VEHICLE GEOLOCATION. The RENTER is expressly informed that the vehicle is fitted with a GPS tracking device that allows its position to be known during the rental period. This information is processed on the basis of the LESSOR legitimate interest (art. 6.1.f GDPR) and exclusively for the following purposes: preventing and recovering the vehicle in the event of theft or failure to return; verifying compliance with the authorised geographical scope; and responding to requests from the authorities. Location data is not used to assess driving behaviour or for commercial purposes, and is kept only for as long as those purposes require.',
        'The data controller is the Company identified in the header. The data will be kept for as long as the contractual relationship is maintained and, subsequently, for the limitation period of the legal actions derived from it. The RENTER may at any time exercise their rights of access, rectification, erasure, opposition, restriction of processing, portability and not to be subject to automated individual decisions with legal effects, by written communication addressed to the LESSOR at the address indicated in the header, accompanied by a copy of an identity document. The RENTER is informed of their right to file a complaint with the Spanish Data Protection Agency (www.aepd.es) if they consider their rights infringed.'
      ]
    },
    ro: {
      title: '14. PROTECȚIA DATELOR CU CARACTER PERSONAL (RGPD / LOPDGDD)',
      body: [
        'În conformitate cu Regulamentul (UE) 2016/679 (RGPD) și cu Legea Organică spaniolă 3/2018 (LOPDGDD), LOCATARUL este informat că datele cu caracter personal furnizate în acest contract, precum și cele generate în cursul executării sale (kilometrajul, nivelul de combustibil, fotografii ale stării vehiculului, procese-verbale de accident și alte date derivate din folosința vehiculului), vor fi prelucrate de LOCATOR, în calitate de operator, în următoarele scopuri și pe următoarele temeiuri juridice: (a) gestionarea integrală a contractului de închiriere și facturarea, pe baza executării contractului (art. 6.1.b RGPD); (b) îndeplinirea obligațiilor legale, fiscale, contabile și comerciale, precum și identificarea conducătorului în fața autorităților administrative și judecătorești, pe baza unei obligații legale (art. 6.1.c RGPD); (c) menținerea istoricului de clienți, recuperarea extrajudiciară și judiciară a sumelor datorate, prevenirea fraudei și securitatea vehiculului și a ocupanților săi, pe baza interesului legitim al LOCATORULUI (art. 6.1.f RGPD).',
        'GEOLOCALIZAREA VEHICULULUI. LOCATARUL este informat în mod expres că vehiculul este dotat cu un dispozitiv de localizare GPS care permite cunoașterea poziției sale pe durata închirierii. Aceste informații sunt prelucrate pe baza interesului legitim al LOCATORULUI (art. 6.1.f RGPD) și exclusiv în următoarele scopuri: prevenirea și recuperarea vehiculului în caz de furt sau nereturnare; verificarea respectării sferei geografice autorizate; și soluționarea solicitărilor autorităților. Datele de localizare nu sunt folosite pentru evaluarea conducerii și nici în scopuri comerciale și se păstrează doar atât timp cât este necesar pentru aceste scopuri.',
        'Operatorul datelor este Societatea identificată în antet. Datele se vor păstra atâta timp cât se menține relația contractuală și, ulterior, pe perioada de prescripție a acțiunilor legale derivate. LOCATARUL poate exercita în orice moment drepturile sale de acces, rectificare, ștergere, opoziție, limitare a prelucrării, portabilitate și de a nu face obiectul unor decizii individuale automatizate cu efecte juridice, prin comunicare scrisă adresată LOCATORULUI la adresa indicată în antet, însoțită de o copie a unui document de identitate. LOCATARUL este informat cu privire la dreptul său de a depune o reclamație la Agenția Spaniolă pentru Protecția Datelor (www.aepd.es) dacă consideră încălcate drepturile sale.'
      ]
    }
  },
  jurisdiction: {
    es: {
      title: '15. JURISDICCIÓN, LEY APLICABLE Y RESOLUCIÓN',
      body: [
        'El presente contrato se rige por la legislación común y civil española, y en particular por las disposiciones del Código Civil, la Ley de Arrendamientos Urbanos en lo que resulte de aplicación supletoria, el Código de Comercio, la Ley sobre Responsabilidad Civil y Seguro en la Circulación de Vehículos a Motor (Real Decreto Legislativo 8/2004), el Código Penal en lo que resulte de aplicación, y cualesquiera otras normas que resulten aplicables al alquiler de vehículos sin conductor.',
        'Para la resolución de cualquier controversia, discrepancia o reclamación derivada del presente contrato o relacionada con él, las partes se someten expresamente a los Juzgados y Tribunales de la ciudad de Madrid (capital), con renuncia expresa a cualquier otro fuero que pudiera corresponderles. No obstante, en el caso de que el ARRENDATARIO tenga la condición de consumidor o usuario, será competente el Juez del domicilio del consumidor.',
        'De conformidad con el artículo 103.l) del texto refundido de la Ley General para la Defensa de los Consumidores y Usuarios, el arrendamiento de vehículos para una fecha o período determinados está excluido del derecho de desistimiento, sin perjuicio de las condiciones de cancelación pactadas con el ARRENDADOR.',
        'El ARRENDADOR dispone de hojas oficiales de reclamación a disposición del ARRENDATARIO, que puede solicitar en el domicilio indicado en la cabecera o por correo electrónico. El ARRENDATARIO puede dirigir cualquier reclamación a la dirección de contacto del ARRENDADOR, que la atenderá en el plazo legalmente previsto.',
        'Si alguna de las cláusulas del presente contrato fuese declarada nula, anulable o ineficaz, total o parcialmente, por cualquier Tribunal, Autoridad u Organismo, el resto de las cláusulas conservarán su plena validez y eficacia, sustituyéndose la cláusula afectada por otra que, siendo lícita, produzca los mismos efectos económicos y jurídicos.'
      ]
    },
    en: {
      title: '15. JURISDICTION, GOVERNING LAW AND SEVERABILITY',
      body: [
        'This contract is governed by the common and civil Spanish legislation, and in particular by the provisions of the Civil Code, the Urban Leases Act in so far as it applies suppletively, the Code of Commerce, the Act on Civil Liability and Insurance in Motor Vehicle Traffic (Royal Legislative Decree 8/2004), the Criminal Code in so far as it is applicable, and any other rules applicable to the rental of vehicles without driver.',
        'For the resolution of any dispute, discrepancy or claim derived from this contract or related to it, the parties expressly submit to the Courts and Tribunals of the city of Madrid (capital), expressly waiving any other jurisdiction to which they may be entitled. However, in the event that the RENTER has the status of consumer or user, the Judge of the consumer\'s domicile will be competent.',
        'In accordance with article 103.l) of the Spanish consolidated text of the General Law for the Defence of Consumers and Users, the rental of vehicles for a specific date or period is excluded from the right of withdrawal, without prejudice to the cancellation terms agreed with the LESSOR.',
        'The LESSOR keeps official complaint forms available to the RENTER, who may request them at the address shown in the header or by email. The RENTER may address any complaint to the LESSOR contact address, which will be handled within the legally established period.',
        'If any of the clauses of this contract were declared null, voidable or ineffective, in whole or in part, by any Court, Authority or Body, the rest of the clauses shall retain their full validity and effectiveness, with the affected clause being replaced by another which, being lawful, produces the same economic and legal effects.'
      ]
    },
    ro: {
      title: '15. JURISDICȚIE, LEGEA APLICABILĂ ȘI SEPARABILITATE',
      body: [
        'Prezentul contract este guvernat de legislația comună și civilă spaniolă, și în special de dispozițiile Codului Civil, Legea Închirierilor Urbane în măsura în care se aplică în mod supletor, Codul Comercial, Legea privind Răspunderea Civilă și Asigurarea în Circulația Vehiculelor cu Motor (Decretul legislativ regal 8/2004), Codul Penal în măsura în care este aplicabil și orice alte norme aplicabile închirierii de vehicule fără șofer.',
        'Pentru soluționarea oricărei dispute, discrepanțe sau reclamații derivate din prezentul contract sau legate de acesta, părțile se supun în mod expres Instanțelor Judecătorești din orașul Madrid (capitală), renunțând în mod expres la orice altă jurisdicție care le-ar putea reveni. Cu toate acestea, în cazul în care LOCATARUL are calitatea de consumator sau utilizator, va fi competent Judecătorul de la domiciliul consumatorului.',
        'În conformitate cu articolul 103.l) din textul consolidat al Legii Generale pentru Apărarea Consumatorilor și Utilizatorilor din Spania, închirierea de vehicule pentru o dată sau o perioadă determinată este exclusă de la dreptul de retragere, fără a aduce atingere condițiilor de anulare convenite cu LOCATORUL.',
        'LOCATORUL pune la dispoziția LOCATARULUI formulare oficiale de reclamație, care pot fi solicitate la adresa indicată în antet sau prin e-mail. LOCATARUL poate adresa orice reclamație la adresa de contact a LOCATORULUI, care o va soluționa în termenul prevăzut de lege.',
        'Dacă oricare dintre clauzele prezentului contract este declarată nulă, anulabilă sau ineficace, în tot sau în parte, de către orice Instanță, Autoritate sau Organism, restul clauzelor își vor păstra pe deplin valabilitatea și eficacitatea, înlocuindu-se clauza afectată cu alta care, fiind legală, produce aceleași efecte economice și juridice.'
      ]
    }
  }
};

const HIGHLIGHTS: Record<ContractLocale, string[]> = {
  es: [
    'El conductor principal asume toda responsabilidad por multas, sanciones, peajes, combustible y daños.',
    'La fianza se devuelve tras la inspección final; puede quedar retenida total o parcialmente.',
    'No devolución, robo, hurto o uso ilegítimo del vehículo puede tener consecuencias penales.',
    'Cualquier daño doloso, vandalismo o acto intencionado es responsabilidad personal del arrendatario.',
    'El vehículo se devuelve con las llaves, documentos y accesorios en el mismo estado de la entrega.',
    'La salida del vehículo fuera de España requiere autorización escrita previa del arrendador.',
    'La suscripción del contrato implica el tratamiento de datos según la LOPDGDD y el RGPD.',
    'Toda controversia se somete a los Juzgados y Tribunales de Madrid (capital).',
    'El arrendatario declara haber leído, comprendido y aceptado todas las cláusulas de este contrato.'
  ],
  en: [
    'The main driver is fully responsible for fines, traffic sanctions, tolls, fuel charges and damage to the vehicle.',
    'The security deposit is refunded after the final inspection; it may be partially or fully retained.',
    'Failure to return the vehicle, theft, robbery or unlawful use may carry criminal liability.',
    'Any wilful damage, vandalism or deliberate act is the personal liability of the renter.',
    'The vehicle must be returned with the keys, documents and accessories in the same state as delivered.',
    'Taking the vehicle outside Spain requires prior written authorisation from the lessor.',
    'Signing this contract implies data processing in accordance with the GDPR and the Spanish LOPDGDD.',
    'Any dispute shall be submitted to the Courts of Madrid (capital).',
    'The renter acknowledges having read, understood and accepted all clauses of this contract.'
  ],
  ro: [
    'Conducătorul principal își asumă întreaga răspundere pentru amenzi, sancțiuni de circulație, taxe de autostradă, combustibil și daune.',
    'Garanția se restituie după inspecția finală; poate fi reținută parțial sau integral.',
    'Nereturnarea, furtul, tâlhăria sau folosința ilicită a vehiculului poate atrage răspundere penală.',
    'Orice daună intenționată, vandalism sau act deliberat este responsabilitatea personală a locatarului.',
    'Vehiculul se returnează cu cheile, documentele și accesoriile în aceeași stare ca la predare.',
    'Ieșirea vehiculului din Spania necesită autorizație scrisă prealabilă a locatorului.',
    'Semnarea acestui contract implică prelucrarea datelor conform RGPD și LOPDGDD spaniol.',
    'Orice litigiu se supune instanțelor judecătorești din Madrid (capitală).',
    'Locatarul declară că a citit, a înțeles și a acceptat toate clauzele acestui contract.'
  ]
};

const ACKNOWLEDGEMENT: Record<ContractLocale, string> = {
  es: 'El ARRENDATARIO declara haber leído, comprendido y aceptado íntegramente las condiciones generales y particulares recogidas en las cláusulas de este contrato, manifestando su conformidad mediante la firma electrónica o manuscrita incorporada al final del documento. La firma tiene los mismos efectos legales que la firma manuscrita prestada en presencia del arrendador, conforme al Reglamento (UE) 910/2014 (eIDAS) y a la legislación española aplicable.',
  en: "The RENTER acknowledges that they have read, understood and fully accepted the general and particular conditions set out in the clauses of this contract, expressing their conformity by means of the electronic or handwritten signature attached at the end of this document. This signature has the same legal effects as a handwritten signature in the presence of the lessor, in accordance with Regulation (EU) 910/2014 (eIDAS) and applicable Spanish law.",
  ro: 'LOCATARUL declară că a citit, a înțeles și a acceptat în întregime condițiile generale și particulare cuprinse în clauzele acestui contract, manifestându-și conformitatea prin semnătura electronică sau olografă atașată la sfârșitul documentului. Semnătura are aceleași efecte juridice ca semnătura olografă dată în prezența locatorului, în conformitate cu Regulamentul (UE) 910/2014 (eIDAS) și legislația spaniolă aplicabilă.'
};

const FOOTER_NOTES: Record<ContractLocale, string[]> = {
  es: [
    'Las cláusulas de este contrato se entregan al ARRENDATARIO en el momento de la firma, junto con una copia firmada por ambas partes y, en su caso, el contrato en formato PDF descargable.',
    'El ARRENDADOR conserva una copia firmada de este contrato durante el plazo legalmente previsto para la prescripción de las acciones legales derivadas del mismo.',
    'La firma electrónica prestada en la plataforma de firma del ARRENDADOR tiene, conforme al Reglamento (UE) 910/2014 (eIDAS) y a la legislación española aplicable, los mismos efectos jurídicos que la firma manuscrita prestada en presencia del ARRENDADOR.'
  ],
  en: [
    'These clauses are delivered to the RENTER at the moment of signing, together with a copy signed by both parties and, where applicable, a downloadable PDF copy of the contract.',
    "The LESSOR keeps a signed copy of this contract for the legally established prescription period of any actions arising from it.",
    "The electronic signature produced on the LESSOR's signing platform has, in accordance with Regulation (EU) 910/2014 (eIDAS) and applicable Spanish law, the same legal effects as a handwritten signature produced in the presence of the LESSOR."
  ],
  ro: [
    'Clauzele acestui contract se predau LOCATARULUI la momentul semnării, împreună cu un exemplar semnat de ambele părți și, dacă este cazul, contractul în format PDF descărcabil.',
    'LOCATORUL păstrează un exemplar semnat al acestui contract pe perioada de prescripție legală a acțiunilor derivate din el.',
    'Semnătura electronică prestată pe platforma de semnare a LOCATORULUI are, conform Regulamentului (UE) 910/2014 (eIDAS) și legislației spaniole aplicabile, aceleași efecte juridice ca o semnătură olografă dată în prezența LOCATORULUI.'
  ]
};

function buildBundle(loc: ContractLocale): ContractClauseBundle {
  return {
    highlights: HIGHLIGHTS[loc],
    acknowledgement: ACKNOWLEDGEMENT[loc],
    footerNotes: FOOTER_NOTES[loc],
    clauses: (Object.keys(I18N) as ClauseId[]).map((id) => ({
      id,
      title: I18N[id][loc].title,
      body: I18N[id][loc].body
    }))
  };
}

export const CONTRACT_CLAUSES: ContractClauses = {
  version: CLAUSES_VERSION,
  defaultLocale: 'es',
  available: ['es', 'en', 'ro'],
  t: {
    es: buildBundle('es'),
    en: buildBundle('en'),
    ro: buildBundle('ro')
  }
};

/**
 * Pick the right locale bundle for a given preferred locale.
 * Falls back to the contract default locale, then to es.
 */
export function pickBundle(
  clauses: ContractClauses,
  preferred?: ContractLocale | string
): { locale: ContractLocale; bundle: ContractClauseBundle } {
  const order: ContractLocale[] = ['es', 'en', 'ro'];
  if (preferred) {
    const p = preferred as ContractLocale;
    if (clauses.t[p]) return { locale: p, bundle: clauses.t[p]! };
  }
  for (const loc of order) {
    if (clauses.t[loc]) return { locale: loc, bundle: clauses.t[loc]! };
  }
  throw new Error('Contract clauses: no locale bundle available');
}
